CREATE DATABASE IF NOT EXISTS olist_leakage_db;
USE olist_leakage_db;

CREATE TABLE IF NOT EXISTS fact_orders_leakage (
    order_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50),
    order_status VARCHAR(20),
    order_purchase_timestamp DATETIME,
    order_approved_at DATETIME,
    order_delivered_carrier_date DATETIME,
    order_delivered_customer_date DATETIME,
    order_estimated_delivery_date DATETIME,
    n_items INT,
    total_price DECIMAL(12,2),
    total_freight DECIMAL(12,2),
    product_id VARCHAR(50),
    seller_id VARCHAR(50),
    total_payment DECIMAL(12,2),
    payment_type VARCHAR(30),
    installments INT,
    review_score INT,
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix INT,
    customer_city VARCHAR(100),
    customer_state VARCHAR(5),
    product_category_name_english VARCHAR(100),
    seller_zip_code_prefix INT,
    seller_city VARCHAR(100),
    seller_state VARCHAR(5),
    is_cancelled BOOLEAN,
    is_late BOOLEAN,
    delay_days INT,
    is_low_review BOOLEAN,
    freight_ratio DECIMAL(6,3),
    is_high_freight_burden BOOLEAN,
    is_payment_issue BOOLEAN,
    leakage_amount DECIMAL(12,2),
    leakage_reason VARCHAR(50),
    order_month VARCHAR(10)
);
